export const ImageList = [
    // "acorn", "almond", "apple", "apricot", "artichoke", "arugula", "asparagus", "avocado", "bacon_lardon",
    // "baking_soda", "banana", "barley", "barley_grain", "basil", "bay_leaves", "beans", "beef_meat", "beet",
    // "belly_lardon", "blackberry", "black_beans", "black_eye_peas", "blood_sausage", "blueberry", "bok_choy",
    // "brazil_nut", "bread_bun", "brie_cheese", "broccoli", "brussels_sprouts", "buckwheat", "bulgur", "ground_beef_minced_steak",
    // "butter", "caraway", "cardamom", "carrot", "cashew", "cauliflower", "caviar",
    // "celery", "chanterelle_mushroom", "chard", "chard_leaf", "cheddar", "cheese", "cherries", "cherry_tomato",
    // "chestnut", "chia", "chicken_meat", "chickling_vetch", "chickpeas", "chili_pepper", "chinese_cabbage", "chive",
    // "chocolate", "cinnamon", "cloves", "coconut", "coffee", "collard", "collard_leaf",
    // "condensed_milk", "coriander", "corn", "cottage_cheese", "couscous", "crab", "cress",
    // "cucumber", "currant", "cuttlefish", "dates", "dill", "dragonfruit", "eel", "egg",
    // "eggplant", "eggs", "endive", "fennel", "fig", "fish", "fish_fillet", "fish_steak", "flax_seed",
    // "flour", "fresh_cheese", "garlic", "ginger", "gnochi", "deer", "grapefruit", "grapes",
    // "green_bean", "green_lentils", "green_peas", "green_pepper", "ham", "hazelnut", "herbs", "honey", "horse_meat",
    // "ice_cream", "juniper", "kale", "kale_leaf", "kefir", "ketchup", "khaki", "kidney_beans",
    // "kiwi", "kohlrabi", "lamb", "lasagne", "leek", "legumes", "lemon", "lettuce", "lettuce_leaf", "lime",
    // "liver", "lobster", "lychee", "macadamia", "mango", "mascarpone", "medlar", "melon", "milk",
    // "millet", "mint", "morel", "mortadella", "mung_bean", "mushroom", "mushroom_oyster", "mussel", "mustard",
    // "nutmeg", "nuts", "oatmeal", "octopus", "oil", "olives", "onion", "orange", "oregano", "oyster", "papaya",
    // "paprika", "parsley", "passion_fruit", "pates", "peach", "peanuts", "pear", "peas", "pecan",
    // "pepper", "pineapple", "pine_nuts", "pinto_beans", "pistachio", "plum", "pomegranate", "poppy_seed",
    // "porcini", "pork", "portobello_mushroom", "potato", "potato02", "powdered_spices", "prunes", "pumpkin",
    // "pumpkin_seed", "quinoa", "rabbit_meat", "radish", "raisins", "raspberry", "red_cabbage", "red_lentils",
    // "red_pepper", "ribs", "rice", "roqueffort", "rosemary", "rye", "rye_grain", "sack_rice", "saffron", "salami", "salmon", "salt", "sardine",
    // "sausage", "sausages", "scallop", "seaweed", "sesame", "shallot", "shark_fins", "shiitake", "shrimp",
    // "sirloin", "skewer", "soft_apricots", "sole", "sorghum", "sour_cream", "soybeans", "spices_bowl",
    // "spinach", "spring_onion", "squid", "star_anise", "steak_meat", "stevia", "stingray", "strawberry", "sugar",
    // "sunflower_seed", "sweet_potato", "syrup", "tangerine", "tarragon", "tea", "thyme", "tomato", "truffle",
    // "tuna", "turkey", "turmeric_curcuma", "turnip", "vanilla", "deer2", "vetch", "vinegar", "walnut",
    // "wasabi", "water", "watercress", "watermelon", "wheat", "whey", "whipped_cream", "white_beans",
    // "wine_red", "wine_white", "winkle", "yeast", "yellow_lentils", "yellow_pepper", "yogurt", "yucca", "zucchini",

    "Abricot",
    "Abricots secs",
    "Agneau",
    "Ail",
    "Algues",
    "Amande",
    "Ananas",
    "Aneth",
    "Anguille",
    "Anis",
    "Artichaut",
    "Asperge",
    "Aubergine",
    "Avocat",
    "Avoine",
    "Banane",
    "Basilic",
    "Blette",
    "Beurre",
    "Bicarbonate",
    "Bigorneau",
    "Blé",
    "Boudin",
    "Boulgour",
    "Brie",
    "Broccoli",
    "Brochette",
    "Cacahuètes",
    "Café",
    "Calamar",
    "Canard",
    "Cannelle",
    "Cardamome",
    "Carotte",
    "Caviar",
    "Celeri",
    "Cerise",
    "Champignon",
    "Chanterelle",
    "Chantilly",
    "Cheddar",
    "Cheval",
    "Chili",
    "Chocolat blanc",
    "Chocolat",
    "Chou chinois",
    "Chou fleur",
    "Chou rave",
    "Chou rouge",
    "Chou",
    "Choux de Bruxelles",
    "Chèvre",
    "Ciboulette",
    "Citron vert",
    "Citron",
    "Citrouille",
    "Clous de girofle",
    "Clémentine",
    "Concombre",
    "Confiture",
    "Coriandre",
    "Courgette",
    "Crabe",
    "Cresson",
    "Crevette",
    "Creme fraiche",
    "Curcuma",
    "Cèpe",
    "Côtes",
    "Datte",
    "Dinde",
    "Eau",
    "Echalotte",
    "Endive",
    "Epices",
    "Epinards",
    "Estragon",
    "Farine",
    "Faux filet",
    "Fenouil",
    "Feta",
    "Figue",
    "Foie",
    "Fraise",
    "Framboise",
    "Fromage blanc",
    "Fromage frais",
    "Fromage",
    "Fruit de la passion",
    "Fruit du dragon",
    "Fruits rouges",
    "Fève",
    "Gibier",
    "Gingembre",
    "Glace",
    "Gland",
    "Gnocchi",
    "Gouda",
    "Graine de citrouille",
    "Graines de chia",
    "Groseille",
    "Haricots blancs",
    "Haricots rouges",
    "Haricots verts",
    "Herbes de Provence",
    "Homard",
    "Huile",
    "Huître",
    "Jambon",
    "Kaki",
    "Kale",
    "Kebab",
    "Kefir",
    "Ketchup",
    "Kiwi",
    "Lait condensé",
    "Lait",
    "Lapin",
    "Lard",
    "Lardons",
    "Lasagne",
    "Laurier",
    "Lentille corail",
    "Lentilles",
    "Levure",
    "Lin",
    "Litchi",
    "Macadamia",
    "Mangue",
    "Marron",
    "Mascarpone",
    "Maïs",
    "Melon",
    "Menthe",
    "Miel",
    "Millet",
    "Moules",
    "Moutarde",
    "Myrtille",
    "Mâche",
    "Mûres",
    "Navet",
    "Noisette",
    "Noix de cajou",
    "Noix de coco",
    "Noix de muscade",
    "Noix de pécan",
    "Noix de Saint Jacques",
    "Noix diverses",
    "Noix du Brésil",
    "Noix",
    "Oeuf",
    "Oignon de printemps",
    "Oignon rouge",
    "Oignon",
    "Olives",
    "Orange",
    "Orge",
    "Origan",
    "Oursin",
    "Pain",
    "Pakchoi",
    "Pamplemousse",
    "Papaye",
    "Paprika",
    "Parmesan",
    "Pastèque",
    "Patate douce",
    "Patate",
    "Pavot",
    "Persil",
    "Petits pois",
    "Pignon de pin",
    "Piment",
    "Pistache",
    "Poire",
    "Poireau",
    "Pois chiches",
    "Poisson",
    "Poivre",
    "Poivron jaune",
    "Poivron rouge",
    "Poivron vert",
    "Pomegranate",
    "Pomme de terre",
    "Pomme",
    "Porc",
    "Poulet",
    "Prune",
    "Pruneau",
    "Pâtes",
    "Pêche",
    "Quinoa",
    "Radis",
    "Raie",
    "Raisin sec",
    "Raisin",
    "Requin",
    "Riz",
    "Roquefort",
    "Roquette",
    "Rosemarin",
    "Safran",
    "Salade",
    "Salami",
    "Sardines",
    "Sarrasin",
    "Sauce piment",
    "Saucisse",
    "Saucisses",
    "Saucisson",
    "Saule",
    "Saumon",
    "Seiche",
    "Seigle",
    "Sel",
    "Semoule de couscous",
    "Shiitake",
    "Sirop d'érable",
    "Sirop",
    "Soja",
    "Steak haché",
    "Steak",
    "Stevia",
    "Sucre",
    "Sésame",
    "Thon",
    "Thym",
    "Thé",
    "Tomate",
    "Tomates cerise",
    "Tournesol",
    "Truffe",
    "Vanille",
    "Viande de boeuf",
    "Viande",
    "Vin blanc",
    "Vin rouge",
    "Vinaigre",
    "Wasabi",
    "Whey",
    "Yaourt",
    "Yucca",
    "Zeste de citron",
    "Bonbons",
    "Brioche",
    "Butternut", "Canneberge", "Cornichon", "Courge", "Dinde", "Edamame", "Frites", "Pop corn", "Porc", "Rumsteak", "Viande"
];
